### ISSUE TITLE
Configure Akamai settings

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/akamai#2]
Settings form for what is currently in the D7 version's configuration form

Sample settings:
-Akamai API URL
-Cache clearing user / password
-Base path 
-Timeout length
-Akamai domain (production, staging)
-Clearing action type default (remove or invalidate option)

Please leverage CMI such that configuration options can be exported by site

**Comment by nerdstein** [comment]
Add menu route

**Comment by cam8001** [comment]
Pull request: https://github.com/d8-contrib-modules/akamai/pull/9

**Comment by cam8001** [comment]
This is integrated in AkamaiConfigForm, both via Purge and standalone.
