### ISSUE TITLE
Manual cache clearing form

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/akamai#3]
A Drupal form that allows a site admin to manually specify...
1. List of URLs to clear
2. Akamai domain (prod, stg)
3. Clearing action type (invalidate, remove)

**Comment by nerdstein** [comment]
Add menu route

**Comment by cam8001** [comment]
Pull request: https://github.com/d8-contrib-modules/akamai/pull/10

**Comment by cam8001** [comment]
Should be all g :) 

Are you at DrupalCon?

**Comment by nerdstein** [comment]
Sadly, no. Wish I was. Did you attend?

**Comment by cam8001** [comment]
Yep, sitting outside waiting to go in to my session now. Once that's done I am planning to go do some coding, it would be great to knock this off this week (at least the open issues).

**Comment by nerdstein** [comment]
Awesome - best of luck! Send me a link to the session if you record it
