### ISSUE TITLE
Akamai Beta Release

### ISSUE THREAD

**Issue by naveenvalecha** [d8-contrib-modules/akamai#33]
Blockers for the Beta Release
1. Automated Tests.
2. Purge URL queuer or other automated queuer
3. [Status tracking of purges](https://github.com/cam8001/akamai/tree/27/track-purge-status)

**Comment by nerdstein** [comment]
I think an Alpha release may be more suitable, but that's just my opinion

**Comment by naveenvalecha** [comment]
Do we have plans to change the APIs or something pending which will break the APIs?

**Comment by cam8001** [comment]
I agree with Adam, there's so many unknowns for Drupal 8 sites in the wild that I wouldn't want to guarantee API stability before we have some feedback from the community.

**Comment by cam8001** [comment]
The module _should_ work with [purge_queuer_url](https://www.drupal.org/project/purge_queuer_url). @neetumorwani is going to test this to make sure we have something workable.

**Comment by cam8001** [comment]
Alpha is released on Drupal.org! Thanks all for all your help!

https://www.drupal.org/node/2698279
