### ISSUE TITLE
Set up a service to manage Akamai

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/akamai#4]
-Set up Drupal service 

-Create a protected function for connecting to Akamai that can be invoked from the other functions of the service
--Pulls from the configuration settings by default
--Can be overridden by function parameters

-Create a public function to clear cache
--Calls the connection function
--Pass parameter of a specific page
--Pull from default settings or from the manually specified values in the manual cache clear form
--Returns response from Akamai, logs response in Watchdog

**Comment by cam8001** [comment]
We probably need to begin integrating Cache Contexts with this, but for now, I'll go ahead with just implementing the Akamai Control Control Utility API: https://developer.akamai.com/api/purge/ccu/overview.html

Do we have a test account for Akamai?

**Comment by cam8001** [comment]
Work is going on in this branch: https://github.com/cam8001/akamai/tree/features/4/akamai-service-container

Note there is a mock service available, provided by Akamai via Apiary. I have committed some code to aid with testing against that, as well as an API blueprint file. In time we should set up a local mock service to run tests (Guzzle has good support for this).

**Comment by cam8001** [comment]
PR https://github.com/d8-contrib-modules/akamai/pull/13

**Comment by cam8001** [comment]
This shoulda been closed a while back. See:

https://github.com/d8-contrib-modules/akamai/blob/8.x-3.x/akamai.services.yml
https://github.com/d8-contrib-modules/akamai/blob/8.x-3.x/src/AkamaiClient.php
