### ISSUE TITLE
Add Akamai Cache Clearing custom block type

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/akamai#6]
1. Can place block on any page (not just nodes but can be a View page or Panelizer page, etc)
2. Only shows / displays for users with "cache clear" permission
3. Renders a button that clears the page's URL

**Comment by cam8001** [comment]
Here's the block. I have still not implemented any actual functionality as still waiting on #4.

https://github.com/d8-contrib-modules/akamai/pull/12
