### ISSUE TITLE
Research task: evaluate cache invalidation strategy

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/akamai#7]
Current D7 behaviors are...
1. If "Expire" is enabled (soft dependency) to register Akamai with Expire and perform cache invalidations inline with Expire's operations
2. If Expire is not enabled, taps into Drupal's hook node update and hook node delete functionality to perform cache invalidation

The purpose of this ticket is to outline the appropriate cache invalidation strategy such that Akamai appropriately invalidates all pages when changes occur

**Comment by cam8001** [comment]
I have spoken to Niels (maintainer of Purge) and @adweingarten and they have done a lot of work and thinking about the best patterns for integrating cache purging with Drupal content workflows. I am gonna go ahead and try integrating with Purge to handle a lot of this kind of stuff.
